version: '3'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_DB: '${DB_NAME}'
    container_name: postgres
    # volumes:
    #   - ./pg-data:/var/lib/postgresql/data
    ports:
      - '6432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: services-api
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
